apiVersion: v1
kind: Service
metadata:
  name: oms-service
  namespace: purchasing-flow
spec:
  selector:
    app: oms-service
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP
