apiVersion: v1
kind: Service
metadata:
  name: rule-engine-service
  namespace: purchasing-flow
spec:
  selector:
    app: rule-engine-service
  ports:
  - protocol: TCP
    port: 8085
    targetPort: 8085
  type: ClusterIP
