apiVersion: v1
kind: Service
metadata:
  name: supplier-service
  namespace: purchasing-flow
spec:
  selector:
    app: supplier-service
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
  type: ClusterIP
