apiVersion: v1
kind: Service
metadata:
  name: uom-service
  namespace: purchasing-flow
spec:
  selector:
    app: uom-service
  ports:
  - protocol: TCP
    port: 8084
    targetPort: 8084
  type: ClusterIP
